parameters_cfg = {
    'a_smile_distance' : 0,
    'a_smile_time' : 0.5,
    'a_headnod_distance' : 16,
    'a_headnod_time' : 1.4,
    'a_leanforward_distance' : 80,
    'a_leanforward_time' : 0,
    'speaker_1': 'woman',
    'speaker_2': 'man',
    'a_AU05_min_mu': 0,
    'a_AU05_min_sd': 1,
    'a_AU17_min_mu': 0,
    'a_AU17_min_sd': 1,
    'a_AU20_min_mu': 0,
    'a_AU20_min_sd': 1,
    'a_AU25_min_mu': 0,
    'a_AU25_min_sd': 1,
    'a_AU05_max_mu': 0,
    'a_AU05_max_sd': 1,
    'a_AU17_max_mu': 0,
    'a_AU17_max_sd': 1,
    'a_AU20_max_mu': 0,
    'a_AU20_max_sd': 1,
    'a_AU25_max_mu': 0,
    'a_AU25_max_sd': 1,
    'a_AU05_mean_mu': 0,
    'a_AU05_mean_sd': 1,
    'a_AU17_mean_mu': 0,
    'a_AU17_mean_sd': 1,
    'a_AU20_mean_mu': 0,
    'a_AU20_mean_sd': 1,
    'a_AU25_mean_mu': 0,
    'a_AU25_mean_sd': 1,
    'a_AU05_va_mu': 0,
    'a_AU05_va_sd': 1,
    'a_AU17_va_mu': 0,
    'a_AU17_va_sd': 1,
    'a_AU20_va_mu': 0,
    'a_AU20_va_sd': 1,
    'a_AU25_va_mu': 0,
    'a_AU25_va_sd': 1,
    'a_posiface_count_mu': 0,
    'a_posiface_count_sd': 1,
    'a_smile_count_mu': 0,
    'a_smile_count_sd': 1,
    'd_word_count_mu': 0,
    'd_word_count_sd': 1,
    'd_word_countprop_mu': 0,
    'd_word_countprop_sd': 1,
    'd_word_uniquecount_mu': 0,
    'd_word_uniquecount_sd': 1,
    'p_delay_mean_mu': 0,
    'p_delay_mean_sd': 1,
    'p_delay_va_mu': 0,
    'p_delay_va_sd': 1,
    'p_delay_min_mu': 0,
    'p_delay_min_sd': 1,
    'p_delay_max_mu': 0,
    'p_delay_max_sd': 1,
    'p_wpm_mean_mu': 0,
    'p_wpm_mean_sd': 1,
    'p_wpm_va_mu': 0,
    'p_wpm_va_sd': 1,
    'p_neutrality_mean_mu': 0,
    'p_neutrality_mean_sd': 1,
    'p_happiness_mean_mu': 0,
    'p_happiness_mean_sd': 1,
    'p_sadness_mean_mu': 0,
    'p_sadness_mean_sd': 1,
    'p_anger_mean_mu': 0,
    'p_anger_mean_sd': 1,
    'p_fear_mean_mu': 0,
    'p_fear_mean_sd': 1,
    'p_neutrality_va_mu': 0,
    'p_neutrality_va_sd': 1,
    'p_happiness_va_mu': 0,
    'p_happiness_va_sd': 1,
    'p_sadness_va_mu': 0,
    'p_sadness_va_sd': 1,
    'p_anger_va_mu': 0,
    'p_anger_va_sd': 1,
    'p_fear_va_mu': 0,
    'p_fear_va_sd': 1
}
